Netlify ecommerce App - minor fixes
stargate/stargate-mongoose-sample-apps pull request #23
Opened 2023-07-16 01:35 UTC by kathirsvn

Netlify ecommerce App - minor fixes after testing and updated README

2023-08-18 21:20 UTC, Yuqi-Du approved these changes
LGTM.
May switch all localhost to 127.0.0.1? Since all higher node version may have issue resolving localhost. But not necessary an item we should take care.
I added a troubleshooting in the repo readme before.

2023-08-18 21:30 UTC, kathirsvn commented
Good point @Yuqi-Du I changed all the instances of `localhost` to `127.0.0.1` now.

2023-08-21 04:35 UTC, Yuqi-Du requested changes

2023-08-21 04:35 UTC, Yuqi-Du commented on netlify-functions-ecommerce/README.md
Small thing, AUTH_URL should be 8081 port.
Related files: README and .env.example

2023-08-21 13:50 UTC, kathirsvn commented on netlify-functions-ecommerce/README.md
Fixed in this commit https://github.com/stargate/stargate-mongoose-sample-apps/pull/23/commits/79176fa71b2634dd3fd2b399afdd6db68b704324.

2023-08-21 15:31 UTC, vkarpov15 reviewed
I made a couple of quick fixes. Most notably, calling `dotenv.config()` is necessary at the start of every possible entrypoint.

I gather that the config file pattern has caused some confusion, so I'm open to switching over to using dotenv since that's a more common pattern for sample apps. However, if we go the dotenv route, we should use dotenv correctly, and we shouldn't mix config patterns. Does that make sense?

2023-08-21 15:31 UTC, vkarpov15 commented on netlify-functions-ecommerce/.env.example
> +#Environment to choose. Possible values: astra, jsonapi
I would advise against using non-standard values for NODE_ENV. So best to not rely on anything other than "local", "development", or "production" for NODE_ENV.

Better to just have an IS_ASTRA environment variable.

2023-08-21 15:31 UTC, vkarpov15 commented on netlify-functions-ecommerce/.config/index.js
> +  module.exports = require('./jsonapi');
In general, I'd recommend getting rid of this file if we're going to use dotenv. Having a multi-layered config setup that mixes different config patterns for a sample app is unnecessarily complex; makes it harder for developers to understand what is going on.

2023-08-21 16:18 UTC, vkarpov15 commented
That works for me @kathirsvn :+1:

2023-08-21 18:32 UTC, kathirsvn commented on netlify-functions-ecommerce/README.md
Hi @Yuqi-Du I fixed this part. Can you please approve this PR if you completed your review?

2023-08-21 20:26 UTC, vkarpov15 approved these changes

2023-08-21 20:33 UTC, Yuqi-Du approved these changes

2023-08-21 20:34 UTC, merged