support astra in typescript-express-reviews sample app
stargate/stargate-mongoose-sample-apps pull request #71
Opened 2023-09-24 21:46 UTC by vkarpov15

Astra support, more consistent `.env` usage, and fix a bug that prevented reviews from showing up as documented in the README

2023-09-28 19:18 UTC, Hazel-Datastax requested changes
Looks good. Could you add an instruction in README.md for the user to create a `.env` file? Like: https://github.com/stargate/stargate-mongoose-sample-apps/tree/main/netlify-functions-ecommerce#netlify-functions-ecommerce

2023-10-09 21:16 UTC, vkarpov15 commented
@Hazel-Datastax fixed, can you please re-review?

2023-12-04 17:33 UTC, vkarpov15 commented
@Hazel-Datastax @Yuqi-Du can you please take a quick look?

2024-01-03 14:52 UTC, Hazel-Datastax approved these changes

2024-01-03 14:56 UTC, merged